### ISSUE TITLE
World browser shows incompatible sessions

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1182]
### Describe the bug?

the world browser displays incompatible sessions if your game is running a different version if you're using plugins or an update comes out you will still be able to see sessions in the world browser that do not match the current version of your game so when you attempt to join you get an incompatible version error

### To Reproduce

Run plugins or wait until there's an update

### Expected behavior

I should only be able to see sessions in the world browser that match my current Resonite version

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/7313a7c7-759d-481b-bf6a-968228b3b6f5)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/00d83fb7-5093-42d2-849e-52a020e66c80)

### Resonite Version Number

2024.1.18.775

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-DAN95E7 - 2024.1.18.775 - 2024-01-18 09_50_18.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13978103/DESKTOP-DAN95E7.-.2024.1.18.775.-.2024-01-18.09_50_18.log)

### Reporters

@epicEaston197

**Comment by epicEaston197** [comment]
> Do you have "show incompatible sessions" turned on in your settings?

nope
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/2823fa9d-b05b-448d-b2d2-0088a0f9f260)

**Comment by epicEaston197** [comment]
> Does the behaviour persist if you enable, and then re-disable that setting, or restart the app, @epicEaston197?

Well now that most people have updated and I don't have any plugins that can test with I cannot Test this

**Comment by Nytra** [comment]
I have noticed this too when testing pre-release builds.

**Comment by Xlinka** [comment]
> > Does the behaviour persist if you enable, and then re-disable that setting, or restart the app, @epicEaston197?
> 
> Well now that most people have updated and I don't have any plugins that can test with I cannot Test this

i now released a plugin if you need to test stuff but the other sessions do show when I'm testing my plugin and this issue occurs and the "show incompatible sessions" is unticked.

https://github.com/Xlinka/Project-Obsidian/releases/tag/v2024.01.21 plugin is here if u want to test with it

**Comment by epicEaston197** [comment]
Well now we can test it with the prerelease build as it is a different version thanks anyway
as you said the problem still occurs

**Comment by ProbablePrime** [comment]
I am accidentally fixing this as a part of some other matters.

**Comment by ProbablePrime** [comment]
This will be in an upcoming build, Thank you

**Comment by Frooxius** [comment]
Fix merged in 2024.2.2.906! Thanks!
