### ISSUE TITLE
LNL prerelease - Relay is not working when using -ForceRelay

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#1200]
### Describe the bug?

When trying to use -ForceRelay in the prerelease build to test using the LNL relays, connection fails - looking at the logs, it appears the relay is closing the connection.

### To Reproduce

Be on the prerelease build and try to connect to a session through the LNL relay (use `-ForceRelay` to force yourself to use the relay).

### Expected behavior

A connection to be established through the relay to the session

### Resonite Version Number

Beta 2024.1.19.1381 (Prerelease)

### What Platforms does this occur on?

Windows

### Log Files

[ERIS - 2024.1.19.1381 - 2024-01-20 13_08_59.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13995921/ERIS.-.2024.1.19.1381.-.2024-01-20.13_08_59.log)

### Reporters

bredo

**Comment by Frooxius** [comment]
No, the relays are updated. I can see the bug relay-side, I'll look into it when I can.

**Comment by Frooxius** [comment]
@bredo228 I've pushed a new client version 2024.1.20.147

Can you please test with that one please and send me the logs?

**Comment by bredo228** [comment]
> @bredo228 I've pushed a new client version 2024.1.20.147
> 
> 
> 
> Can you please test with that one please and send me the logs?

Will do so in the next hour or so, not at a computer right now.

**Comment by bredo228** [comment]
@Frooxius looks like it's still happening

log:
[ERIS - 2024.1.20.147 - 2024-01-20 17_18_23.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13996643/ERIS.-.2024.1.20.147.-.2024-01-20.17_18_23.log)

**Comment by bredo228** [comment]
[glaceon - 2024.1.20.147 - 2024-01-20 04_15_19.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13996649/glaceon.-.2024.1.20.147.-.2024-01-20.04_15_19.log)
log from the host side (headless)

**Comment by Frooxius** [comment]
@bredo228 Thanks! I've pushed an update `2024.1.20.559`, this should fix this hopefully.

Can you try that one please?

**Comment by bredo228** [comment]
> @bredo228 Thanks! I've pushed an update `2024.1.20.559`, this should fix this hopefully.
> 
> Can you try that one please?

Looks like it's functioning as intended now!

**Comment by Frooxius** [comment]
Ah perfect! Thanks, I'm closing this now!

**Comment by bontebok** [comment]
Confirmed with @stiefeljackal that the update corrected the ability to connect over the LNL_Relay server.
