### ISSUE TITLE
Contacts+ headless sessions don't show in contacts list

### ISSUE THREAD

**Issue by liny-fox** [Yellow-Dog-Man/Resonite-Issues#136]
### Is your feature request related to a problem? Please describe.

On the previous platform if a headless hosted world that was set to contacts plus it would show up in the worlds list of worlds the headless was in, now it is hidden, making the C+ setting a little broken.

### Describe the solution you'd like

Revert the behavior back to how it was on the previous platform to make joining C+ headless sessions easier.

### Describe alternatives you've considered

Setting it to some other more restricted mode like contacts only, joining it, then manually chancing it to contacts plus once in, but that reverts back to the original problem once everyone leaves or the server resets or crashes.

**Comment by liny-fox** [comment]
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7400549/30432e62-2b45-40cd-9473-45d81997af02)
The middle area, the session only shows up if the world is set to contacts only, but if set to contacts plus it vanishes from the session list

**Comment by liny-fox** [comment]
Not exactly sure how much log files will help in this case but sure, let me get a clean session.

[resonite - 2023.10.17.464 - 2023-10-17 20_48_40.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12956731/resonite.-.2023.10.17.464.-.2023-10-17.20_48_40.log)
[CHRIS-LAPTOP - 2023.10.17.464 - 2023-10-17 13_48_42.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12956862/CHRIS-LAPTOP.-.2023.10.17.464.-.2023-10-17.13_48_42.log)

First is clean startup of the headless in contacts only then switching it to contacts plus and shutting it down, second is my client starting up, searching for my headless and then executing the above steps on the headless and shutting down my client.

**Comment by liny-fox** [comment]
Ah, fair enough. hope they help

**Comment by liny-fox** [comment]
This was working for a short time today, then I restarted my headless to change the config to reflect it thinking it was fixed and it sadly was not, so I'm wondering if it is an intermittent thing or a backend thing.

**Comment by liny-fox** [comment]
I managed an interesting session, if I log in, contacts+ sessions do show up in the world browser and contacts list at first for a few minutes then disappear. However sessions switched from contacts to contacts+ just hide from view.

Attached is a log file from this session of logging in, looking at the world browser of a world that had a contacts+ session showing, going to the contacts tab, looking up the host of it, seeing its open worlds there as well, looking at my headless host and switching it from contacts to contacts+ and watching its worlds list go blank, then going back to the other host and observing its worlds still showing its public world and its contacts+ world before the contacts+ world poofed.

[CHRIS-LAPTOP - 2023.11.18.1263 - 2023-11-20 15_10_00.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13420198/CHRIS-LAPTOP.-.2023.11.18.1263.-.2023-11-20.15_10_00.log)

**Comment by Nytra** [comment]
I think this is still happening on the latest build. I have a headless log file for this. You can see in the log that after the access level is set to Contacts Plus (FriendsOfFriends) it does not broadcast the session info to AllContacts, but does broadcast it slowly to (random?) individual contacts.

[DESKTOP-H976HO2 - 2024.4.26.1258 - 2024-04-28 02_51_36.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15140499/DESKTOP-H976HO2.-.2024.4.26.1258.-.2024-04-28.02_51_36.log)

**Comment by Redd56** [comment]
![Image](https://github.com/user-attachments/assets/6e0b8dea-5070-415e-8e76-e5d84282b5bd) so.. its seems to be working now? the invites are for a different session id and the headless is set to contacts plus im checking with others tho to concure that its resolved itself
