### ISSUE TITLE
Sending lots of WebSocket messages kicks you from a world/crashes the world

### ISSUE THREAD

**Issue by hazre** [Yellow-Dog-Man/Resonite-Issues#19]
### Describe the bug?

Previously I was using WebSockets in the old platform as my own custom face tracking solution and it worked fine there but in resonite when you send websocket messages too fast after a minute or two you will get kicked or crash the world if you're hosting it. And you will get this error:

```
9:25:11 PM.470 ( 45 FPS)    Unhandled Exception when updating world: Danger. State Running, Refresh Stage: ProtoFluxEvents, Init State: Finished, SyncTick 28147, StateVersion: 2407590
```
### To Reproduce

repro made by @art0007i

[hazre_broken_ws.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12899669/hazre_broken_ws.zip)

reproduction: extract the zip into a folder then run

```
npm install
npm start
```
and spawn this item in game and click the connect call

```
resrec:///U-art0007i/R-2F100B44A418D299A4E5C90BEABA32ECC3C85AE259CAFBF75555A1C45DB35D33
```

### Expected behavior

To not get kicked or crash the world.

### Screenshots

Screenshot of repo:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/37149950/514ef956-249a-4909-b659-408b6541514f)

### Resonite Version Number

Any

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

[MONOCHROME_-_2023.9.27.1421_-_2023-09-29_21_12_34.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12899679/MONOCHROME_-_2023.9.27.1421_-_2023-09-29_21_12_34.log)

### Reporters

@hazre 
@art0007i

**Comment by kulzae** [comment]
Adding this occurs for me as well. behavior is not consistent and is not always due to sending websocket messages at a high rate. once the issue occurs it will repetitively occur untill the client is restarted.

This is a log file of it occuring three times in a short amount of time
[RENEGADE_-_2023.10.10.1407_-_2023-10-12_18_06_08.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12899745/RENEGADE_-_2023.10.10.1407_-_2023-10-12_18_06_08.log)

**Comment by orange3134** [comment]
I often have this problem too.
I am not sure if it is related to the frequency of Websocket sending.
If I am sending websockets continuously, I get this error after a few minutes and the world crashes.
`21:21:11.309 ( 61 FPS)	Unhandled Exception when updating world: オレンジの家. State Running, Refresh Stage: ProtoFluxEvents, Init State: Finished, SyncTick 6233, StateVersion: 12466`

The full text of the log is this.
[MENTAIKO - 2023.11.18.1263 - 2023-11-20 21_18_19.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13415063/MENTAIKO.-.2023.11.18.1263.-.2023-11-20.21_18_19.log)

**Comment by Frooxius** [comment]
I'll have a look into this soon. From the logs it looks like there's some lifecycle errors, where it seems to be wanting to running events for something that was deleted, but I'm not quite sure where they're coming from.

There's one thing I needed to do that hasn't been done yet, which is wrapping ProtoFlux errors so they do not crash the entire session and just get logged, which would at least prevent the crashes (and many others).

**Comment by Frooxius** [comment]
I've fixed this in 2023.12.13.87, thanks for the report! It was a race condition making things weird.

**Comment by charlie-sans** [comment]
hey @shiftyscales this issue still affects some people such as me that use them for projects
