### ISSUE TITLE
User is Online notifications are being spammed.

### ISSUE THREAD

**Issue by FroppyVR** [Yellow-Dog-Man/Resonite-Issues#2178]
### Describe the bug?

Following the Sociable status hotfix, the notifications for contacts being online is now being spammed, the rate is fairly slow however. About a few minutes between repeats, so I can't capture any good video of it.  

### To Reproduce

Launch the game, sit in your cloud home and watch the notifications. Give it a few minutes and you will start seeing repeats. It's slow but consistent. 

### Expected behavior

We shouldn't be seeing the same user is online. 

### Screenshots

N/A, the notifications are too slow to really show the repeats in a screenshot. 

### Resonite Version Number

2024.5.31.72

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-ROAF3GP - 2024.5.31.72 - 2024-05-30 22_30_01.log](https://github.com/user-attachments/files/15507810/DESKTOP-ROAF3GP.-.2024.5.31.72.-.2024-05-30.22_30_01.log)

### Additional Context

N/A

### Reporters

@Froppy

**Comment by Frooxius** [comment]
The few minutes between repeats seems normal here - the cooldown is set to 1 minute. Every few minutes isn't really what we'd consider "spam" in the usual sense.

I'd need more information to figure out what's going on here.

- Is this the same person that's changing their status to Online?
- Is the person actually changing their online status from online to away/busy/invisible and then back online? Or are they online the whole time?

**Comment by FroppyVR** [comment]
I've seen repeats from multiple people on my list:
- Dante 
- Gareth
- badhaloninja
- code807
- Nexulan

and a few others, but none of them are switching status. I'm watching my contacts menu now and everyone is green. 

I have two contacts on sociable status, and I'm not seeing "is now online" spam from them, so this may only be affecting online status. I'll continue watching for them, but nothing yet.

**Comment by XDelta** [comment]
I've been noticing the same here, seeing online notifications for a good couple dozen people, I doubt that this many people are toggling their own statuses. I picked one person and watched just for their own status popping up again, saw a second about a minute later, saw another for them ~2m45s after, once more a little after a minute. While watching this one, definitely have seen several others repeatedly showing up as well but haven't been keeping track of time between.

Watching the Contacts page as well, it doesn't appear that these user are swapping online statuses.

**Comment by Frooxius** [comment]
Hold on, I think I know what it might be. I've been going through the code and I think that the notifications aren't getting filtered right.

**Comment by XDelta** [comment]
So far, looks to only be from those set to online, not seeing any come from sociable. Although there is only 5 on my friends list with that status compared to ~30 set as online

**Comment by badhaloninja** [comment]
I have not switched from Online since before the hotfix (2024.5.31.72) came out

**Comment by Frooxius** [comment]
Ok should be fixed in 2024.5.31.202, thanks!

**Comment by Azavit** [comment]
This seems like it is still an issue in very 2024.5.31.202 but only with a few users. (unless this is a different issue with similar effect)

I was in a world with Gawdl3y and the Sociable Status kept popping up for them despite them clearly not messing with the setting.

This was Noticeable by both me and Waterfox (as well as others on mine and Waterfox's friends... but Gawdl3y was the first one we can confirm wasn't messing with the setting)

This seemed to happen about once every 10 minutes.

**Comment by Nytra** [comment]
It could be the contact temporarily showing offline bug https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/739

**Comment by shiftyscales** [comment]
I think it likely could #739 @Azavit @Nytra. That issue is in need of getting more timestamped (press F3 when the issue is observed) logs from both ends/users showing the issue as it occurred.
