### ISSUE TITLE
Clicking on tools in multiplayer causes the game to crash.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#2493]
### Describe the issue.

When clicking on a tool in multiplayer, the game dies. Oddly enough this doesn't happen when you equip the desktop tools with the number row.

### To Reproduce

Go into a session with another user, click on any tool, the game crashes.

### Expected behavior

For the tool to not crash the session.

### Resonite Version Number

2024.7.7.1295

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Quest Pro

### Log Files

[DESKTOP-QBGCSAQ - 2024.7.7.1295 - 2024-07-07 15_51_09.log](https://github.com/user-attachments/files/16121072/DESKTOP-QBGCSAQ.-.2024.7.7.1295.-.2024-07-07.15_51_09.log)

### Reporters

ModernBalloonie , epicEaston197

**Comment by ModernBalloonie** [comment]
It seems that equipping the tool isn't causing the issue, rather, it is when you click on the tool, it seems it's something to do when the radial menu is generated or something. This doesn't occur when you grab the tool and equip it that way.

**Comment by ModernBalloonie** [comment]
This also happens when trying to equip avatars.

**Comment by bredo228** [comment]
Reproduced using headless. Hit F3 before and after world crash.

Graphical client: 
[DYSNOMIA - 2024.7.7.1295 - 2024-07-08 11_10_04.log](https://github.com/user-attachments/files/16121094/DYSNOMIA.-.2024.7.7.1295.-.2024-07-08.11_10_04.log)

Headless:
[x220tablet - 2024.7.7.1295 - 2024-07-08 11_10_03.log](https://github.com/user-attachments/files/16121096/x220tablet.-.2024.7.7.1295.-.2024-07-08.11_10_03.log)

**Comment by Frooxius** [comment]
This should be fixed with 2024.7.8.1130, thanks!

**Comment by epicEaston197** [comment]
Just tested it on the latest build it has not been resolved I still crashed when I tried to equip it by clicking on it

**Comment by Zyro1331** [comment]
Me and @epicEaston197 are testing currently and discovered a world crash occurs when something remotely spawns the context menu. Laser Equipping tools, Clicking on Avatars, Clicking on Avatar Anchors will cause an instant world crash. Though, clicking on the "Action button" in an Inspector (the menu that appears to reset a value) doesn't cause an immediate world crash.

**Comment by Frooxius** [comment]
Can you provide logs for the new crashes please?

**Comment by Zyro1331** [comment]
[MANGOVRG - 2024.7.8.1053 - 2024-07-08 11_59_56.log](https://github.com/user-attachments/files/16133613/MANGOVRG.-.2024.7.8.1053.-.2024-07-08.11_59_56.log)
I had another world crash occur after importing an image, selecting it, and then spawning an inspector. Not sure exactly what in that sequence caused it.
@epicEaston197 please upload your log as well too as you had other scenarios trigger local world crashes.

**Comment by epicEaston197** [comment]
> [MANGOVRG - 2024.7.8.1053 - 2024-07-08 11_59_56.log](https://github.com/user-attachments/files/16133613/MANGOVRG.-.2024.7.8.1053.-.2024-07-08.11_59_56.log) I had another world crash occur after importing an image, selecting it, and then spawning an inspector. Not sure exactly what in that sequence caused it. @epicEaston197 please upload your log as well too as you had other scenarios trigger local world crashes.

[EPICEASTON197 - 2024.7.8.1130 - 2024-07-08 15_00_12.log](https://github.com/user-attachments/files/16133642/EPICEASTON197.-.2024.7.8.1130.-.2024-07-08.15_00_12.log)

**Comment by Zyro1331** [comment]
Oh, that's interesting. My version number doesn't match, Steam gave me a slightly out-of-date build under my nose. 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/da72b9ab-9da5-4ea0-90da-51eaa7ca6c14)

**Comment by Zyro1331** [comment]
Okay so I'm finally on the latest build, we have also discovered that loading a StaticTexture2D in an inspector causes a world crash too. I'll write that into it's own issue along with an upload of my log.

**Comment by bredo228** [comment]
Can confirm clicking on an avatar / tool to equip still crashes in build 2024.7.8.1130

Log:
[DYSNOMIA - 2024.7.8.1130 - 2024-07-09 08_44_31.log](https://github.com/user-attachments/files/16134381/DYSNOMIA.-.2024.7.8.1130.-.2024-07-09.08_44_31.log)

**Comment by Frooxius** [comment]
Okay I think this is fully fixed in 2024.7.8.1285 now. If not let me know! THanks!

**Comment by bredo228** [comment]
Tested with avatar and tools, both seem to work fine. Thank you!
