### ISSUE TITLE
Texture references don't spawn inspectors correctly

### ISSUE THREAD

**Issue by Zyro1331** [Yellow-Dog-Man/Resonite-Issues#2510]
### Describe the issue.

When holding a reference to a StaticTexture2D or StaticTexture3D and pulling the trigger to create a Texture Inspector, it will instead spawn at the world origin instead of in-front of the user.
I was unable to replicate the issue with Material orbs or Procedural Textures, just StaticTexture components inhibit the behavior. 

### To Reproduce

1. Grab a Material Tool and select the floor. (Like the Local Home ground)
2. Open your context menu and click Edit Material.
3. Try to pull the texture out of the material.

You'll notice that the newly spawned Inspector just appears half-way in the ground instead of appearing correctly.

### Expected behavior

The Inspector should spawn in front of the user, instead of going to the world origin.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/6b4fdf14-3c0d-4951-8c9e-71843c085a18

Here's a video demonstrating the behavior. 

### Resonite Version Number

Beta 2024.7.8.1285 

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MANGOVRG - 2024.7.8.1285 - 2024-07-08 16_07_47.log](https://github.com/user-attachments/files/16135216/MANGOVRG.-.2024.7.8.1285.-.2024-07-08.16_07_47.log)

### Additional Context

As stated earlier, I couldn't recreate the issue using Procedural textures. Only StaticTexture components behave this way.
Materials, Audio Clips, and other types of assets work completely fine. 

### Reporters

@epicEaston197
@zyro1331

**Comment by Frooxius** [comment]
This should be fixed in 2024.7.9.1044, thanks for report!

**Comment by epicEaston197** [comment]
This issue is not resolved this happens with worker inspectors for components now

**Comment by Frooxius** [comment]
Can you provide logs for new issue please?

**Comment by epicEaston197** [comment]
> Can you provide logs for new issue please?

I'm gathering them now

**Comment by epicEaston197** [comment]
Okay never mind steam gave me an outdated build
