### ISSUE TITLE
[Photon Dust] Particle system performance degraded on converted particle systems

### ISSUE THREAD

**Issue by bontebok** [Yellow-Dog-Man/Resonite-Issues#3355]
### Describe the issue.

Photon Dust appears to be less performant than Unity for simple firework particles. Might be directly related to the performance issue that @orange3134 reported in #3301.

### To Reproduce

This world linked below contains 25 firework launchers made by Orange. With legacy (Unity) particles, the particle system holds up well and delivers nearly no frame drop. When upgrading to Photon Dust, the new particle system sees significant frame drops during the particle display. This has been reproduced with similar results on Ryzen APU, an Nvidia GTX 3080, and an NVidia GTX 4070.

Compare the performance of launching all 25 fireworks simultaneously from legacy (Unity) particles to Photon Dust particles. You can reduce the number of fireworks and still see the performance degradation. You can also fire more simultaneously to see how the performance degradation stacks.

resrec:///U-Rucio/R-e1b021bc-82c3-4389-a0b9-e51484dea75b

### Expected behavior

The Photon Dust particle system should perform as well as or better than Unity.

### Screenshots

Legacy Particles (Unity)
https://github.com/user-attachments/assets/848337f0-8f56-47ca-b248-39af00067d5e

Photon Dust Particles
https://github.com/user-attachments/assets/0c7c9aba-c89a-4896-8a27-9bdab7e9270e

### Resonite Version Number

2024.12.13.1342 (Prerelease)

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop & Valve Index

### Log Files

[DESKTOP-4UDK5SF - 2024.12.13.1342 - 2024-12-13 19_17_26.log](https://github.com/user-attachments/files/18133055/DESKTOP-4UDK5SF.-.2024.12.13.1342.-.2024-12-13.19_17_26.log)

### Reporters

First identified by @epicEaston197 when testing Creator Jam worlds on Photon Dust. Easton reported a loss of frame rate in both the New Year's Eve 2023 and New Year's Eve 2024 worlds when the fireworks appeared. Other reporters are FoxBox, StiefelJackal, Stellanora, Player_Kode, and Storm_Dpd who provided feedback for Photon Dust prerelease testing.

**Comment by epicEaston197** [comment]
You can see the particle spirals look correct
![Image](https://github.com/user-attachments/assets/d6452ba8-fd0f-46b7-b243-6c045bb9bd77)
This is later in the sequence to where there are trails and particles dropping from the sky and it seems to be a bit too much for the particle system to simulate as the spinning particles at the base of the flower Is now updating slower
![Image](https://github.com/user-attachments/assets/68863edd-ffb8-4760-a46d-a2f8afa0124c)

**Comment by bontebok** [comment]
An additional observation - I made a copy of the world and disabled all particle trails on the fireworks. Since some fireworks only use trails, the performance has improved, however a performance drop is still seen from legacy to Photon Dust.

Also interesting is the visual difference between the legacy particle system and Photon Dust particles.

Here's the world rec for the trails disabled - resrec:///U-Rucio/R-fc879817-f905-4c74-9155-85f097bbd3b9

Legacy particle system (no trails)
https://github.com/user-attachments/assets/17173302-0922-4cf5-abca-d8b283dc5ba7

Photon Dust (no trails)
https://github.com/user-attachments/assets/f1ff9a54-5cc4-4f71-a902-737e8b3b1c79

**Comment by Frooxius** [comment]
Thanks for the report! I've done some testing and I do think this has same underlying cause as #3301 after all, since addressing that one seems to fix this one too. But I'm going to keep it open until I'm fully sure.

Cross-posting findings from the other thread here:

> I've got this mostly fixed up. It turns out that it's not actually a performance issue, but mostly a content conversion issue - notably the trail lifetime from particle size wasn't converting at all, so trails ended up 10x longer than they were supposed to.
> 
> This resulted in PhotonDust having to update about 10x more trail data than legacy system and it also had to render 10 times more trail geometry, both of which contributed to the significantly lower performance. After fixing the conversion it runs pretty smooth.
> 
> There are a few things I found that can help speed things up a bit more, so I'll try to get those sorted out as well before I close this.

**Comment by Frooxius** [comment]
@bontebok I've pushed a fix to the related issue in 2024.12.18.477! It seems to run way better with this build on my end. 

Are you able to check and verify on your end please?

**Comment by epicEaston197** [comment]
I'm still getting issues with the flower object
![Image](https://github.com/user-attachments/assets/0d83a41d-9f67-49ce-b361-1fe12941a207)

**Comment by Frooxius** [comment]
@epicEaston197 This is the wrong issue for that, this is for performance degradation. 

For visual differences make a separate issue please.

**Comment by epicEaston197** [comment]
> [@epicEaston197](https://github.com/epicEaston197) This is the wrong issue for that, this is for performance degradation.
> 
> For visual differences make a separate issue please.

No this is related the performance degradation is causing the particle system to slow down significantly I'm sorry for making that not clear

**Comment by bontebok** [comment]
> [@bontebok](https://github.com/bontebok) I've pushed a fix to the related issue in 2024.12.18.477! It seems to run way better with this build on my end.
> 
> Are you able to check and verify on your end please?

The particle framerate overall has improved, but the reduction in the rendering rate of the particles is still much lower when comparing to Legacy/Unity for high numbers of particles, or a moderate amount of particles with trails. The performance seems to be about 1/10th - 1/15th of the rate of particle updates comparing both particle systems together.

To reproduce this, we created a legacy particle using the Legacy Particle system from the inspector, and created a PhotonDust particle system with matching parameters. We set the quantity of the system to 100,000 and set the emitter to 100,000 with a life of 1 second. The Legacy Particle System was able to produce the amount easily with a very low little frame drop (~75fps to ~70fps), however the PhotonDust system was only able to produce particle updates at a rate of about 5 fps.

**Comment by Frooxius** [comment]
@bontebok I'm not sure at this point, I need more data and replication items to look into things and investigate underlying causes.

Overall the goal is to get PhotonDust as performant as possible, while also weighing it against other factors - how much time we need to invest into things we'll keep (FrooxEngine/PhotonDust side) vs how much time into things we'll ditch in the future (Unity integration & rendering submission) vs how much problems they're causing right now.

For context, there are some limitations while we're still tied to Unity due to us having to pump the data into it for rendering. I have an alternate approach in mind using compute buffers to submit the particle data for rendering, but that requires to overhaul all our shaders to support those. This is a bigger chunk of work, so I want to avoid that if possible, because the work will be invalidated once we do switch to Sauce.

So currently the dilemma I'm facing is - is it worth putting extra weeks of time into reworking the rendering side with the compute buffer approach or not?

To make that decision, I need to know how much of the performance issues are actually caused by this part, vs other thing - and having more issues and replication items helps make that decision. It would be helpful in that regard to make an issue to fix it. I can't promise you I'll be able to fix it while we're still tied to Unity, but I can promise you I'll try.

It might also turn out to be something completely else - e.g. with this and #3301, I went into the issue thinking there's an issue with the submission mechanism causing performance degradation, only to find that majority of the overall FPS drop is something completely different - the conversion generating & updating 10x amount of trail data over legacy - the underlying issue being something completely different.

It's possible that with what you're seeing there's something "silly" like that causing issues that can be easily fixable - but I won't know either way until I look into it.

**Comment by bontebok** [comment]
> Overall the goal is to get PhotonDust as performant as possible, while also weighing it against other factors - how much time we need to invest into things we'll keep (FrooxEngine/PhotonDust side) vs how much time into things we'll ditch in the future (Unity integration & rendering submission) vs how much problems they're causing right now.
> 
> For context, there are some limitations while we're still tied to Unity due to us having to pump the data into it for rendering. I have an alternate approach in mind using compute buffers to submit the particle data for rendering, but that requires to overhaul all our shaders to support those. This is a bigger chunk of work, so I want to avoid that if possible, because the work will be invalidated once we do switch to Sauce.
> 
> So currently the dilemma I'm facing is - is it worth putting extra weeks of time into reworking the rendering side with the compute buffer approach or not?
> 
> To make that decision, I need to know how much of the performance issues are actually caused by this part, vs other thing - and having more issues and replication items helps make that decision. It would be helpful in that regard to make an issue to fix it. I can't promise you I'll be able to fix it while we're still tied to Unity, but I can promise you I'll try.

Thanks Froox for expanding your thoughts. I understand your dilemma entirely.. As most of the engineering work you've already put in for PhotonDust will have the most realized benefit once Sauce is implemented, adding enhancements that will only benefit Unity would be a wasted effort.

The reason I am most concerned for the performance of PhotonDust now is that I have a fear that the Resonite Team may decide in the future to replace Unity particles with PhotonDust while we remain tethered to Unity. I don't think this is the intention based on the above, however since there is no guarantee as to what decisions the Resonite Team makes, it's a fear I have nevertheless.

@Stellanora has submitted #3401 which can replace this one for the overall performance concerns. For now, you can close this as resolved as the trail issue that was the primary cause for the degraded performance has been resolved.

PS: I may submit one more issue regarding a visual rendering difference with a specific particle configuration as that might be something that would carry over to Sauce as it does not relate to performance.

Thank you!

**Comment by Frooxius** [comment]
@bontebok Thank you for the further clarification.

I think there's misunderstanding of the plan though, why PhotonDust is being implemented and why I have the dilemma in the first place.

As I mentioned in the announcements, the testing post and other places , removing the Unity system is the goal here (and it's been since the beginning) - it will happen and it needs to happen as part of the performance updates. That decision has already been made. 

The Unity particle system prevents us from separating the engine out into its own process  (running under .NET 9) and thus slowly removing the tethering to Unity, bit by bit.

If we don't, then it halts the whole process.

This is the reason I'm having the dilemma - I'm essentially gauging how much effort is needed to be put into Unity side for rendering PhotonDust before we remove the legacy system.

I don't want to spend too long on it, but also depending on how big the issues are, I might need to to carry us over.

**Comment by Frooxius** [comment]
I'm closing this one, since the particular cause in this one was addressed. The other issue that focuses more on the overall simulation update rate is still open.
