### ISSUE TITLE
PhotonDust sometimes completely dies and causes every particle system in the world to freeze when deleting a particlesystem with lots of particles.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#3507]
### Describe the bug?

When spawning a bunch of large particle systems, and then deleting one of them, Sometimes it causes all particles in the world to freeze, causing every photondust system to freeze, until you leave and rejoin the world.

### To Reproduce

Spawn this ResonitePackage.
[ProblemBox.zip](https://github.com/user-attachments/files/18370503/ProblemBox.zip)

Spawn it a few times

Then try to delete one of them, If deleting one doesn't work, try deleting them until you get the bug.

### Expected behavior

For PhotonDust systems to not die.

### Screenshots

https://github.com/user-attachments/assets/434e1dd5-c8b6-4491-a82a-b5060281d9af

### Resonite Version Number

2025.1.9.1412

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

[DESKTOP-QBGCSAQ - 2025.1.9.1412 - 2025-01-09 20_10_43.log](https://github.com/user-attachments/files/18370513/DESKTOP-QBGCSAQ.-.2025.1.9.1412.-.2025-01-09.20_10_43.log)

### Reporters

ModernBalloonie

**Comment by ModernBalloonie** [comment]
Figured i'd also add that it happens on the build Beta 2025.1.10.1386 too, just tested it.

I also think I found one of the errors.

```
4:51:27 PM.278 ( 70 FPS)	Exception running OnDispose():
System.NullReferenceException: Object reference not set to an instance of an object
  at FrooxEngine.PhotonDust.ParticleSystem.OnStyleConfigurationChanged (FrooxEngine.PhotonDust.ParticleStyle style) [0x00000] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at FrooxEngine.PhotonDust.ParticleStyle.OnDispose () [0x00010] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at FrooxEngine.Worker.Dispose () [0x0000a] in <a23d31536e834b7da8b00520a555d6b4>:0 

  at System.Environment.get_StackTrace () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
  at Elements.Core.UniLog.Error (System.String message, System.Boolean stackTrace) [0x00000] in <5879b941f80148f9b21f32dd0c761cf5>:0 
  at FrooxEngine.Worker.Dispose () [0x00000] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at FrooxEngine.ComponentBase`1[C].InternalRunDestruction () [0x00000] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at FrooxEngine.UpdateManager.ProcessDestruction (FrooxEngine.IUpdatable updatable) [0x00000] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at FrooxEngine.UpdateManager.RunQueue[T] (System.Collections.Generic.Queue`1[T] queue, System.Action`1[T] action) [0x00000] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at FrooxEngine.UpdateManager.RunDestructions () [0x00000] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at FrooxEngine.World.RefreshStep () [0x00000] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at FrooxEngine.World.Refresh () [0x00000] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at FrooxEngine.WorldManager.UpdateStep () [0x00000] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at FrooxEngine.WorldManager.RunUpdateLoop () [0x00000] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at FrooxEngine.Engine.UpdateStep () [0x00000] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at FrooxEngine.Engine.RunUpdateLoop () [0x00000] in <a23d31536e834b7da8b00520a555d6b4>:0 
  at UnityFrooxEngineRunner.FrooxEngineRunner.UpdateFrooxEngine () [0x00000] in <ef1ab222b4fa49d89ef699535f7e27b9>:0 
  at UnityFrooxEngineRunner.FrooxEngineRunner.Update () [0x00000] in <ef1ab222b4fa49d89ef699535f7e27b9>:0 
```

**Comment by Frooxius** [comment]
I think I've fixed this in 2025.1.14.6, but can you test plese?

**Comment by ModernBalloonie** [comment]
![Image](https://github.com/user-attachments/assets/ff28d97a-882f-402d-a4d2-90e25f157ca2)

Hmm, it still happens, I'll get another log.

**Comment by ModernBalloonie** [comment]
[DESKTOP-QBGCSAQ - 2025.1.14.6 - 2025-01-13 19_51_11.log](https://github.com/user-attachments/files/18405094/DESKTOP-QBGCSAQ.-.2025.1.14.6.-.2025-01-13.19_51_11.log)

Here's a new log.

**Comment by shiftyscales** [comment]
Removing the "awaiting fix confirmation" label- it sounds like there are still conditions in which this issue can occur, @Frooxius.

**Comment by Frooxius** [comment]
I've fully fixed this in 2025.1.28.1216. Thanks for report!
