### ISSUE TITLE
Reflection Probe - Probetype "OnChange" breaks / becomes very heavy

### ISSUE THREAD

**Issue by Readun** [Yellow-Dog-Man/Resonite-Issues#3819]
### Describe the bug?

There seems to be a big issue with reflection probes with the probe type "OnChange", causing them to get "Stuck" and when they are stuck, they are causing quite a bit of a system load.

With "Stuck" I mean they seem to get very bright or just stay at the last rendered reflection they were rendering.

### To Reproduce

Have a couple reflection probes "OnChange" set to something that maybe changes slowly over time, like a sun rotating. (About ~ 0.2-0.5 updates per second).

Ways the Probe got stuck on me:
- Defocusing and refocussing the world
- Disabling and enabling the Slot the probes are on.

In my homeworld with 3 probes at a 128 resolution, it caused my FPS in desktop (With SteamVR) to go from 120 FPS down to 15-20 fps.

Ways to "Unstuck" the probes and fix the lag aswell:
- Changing the ProbeType from OnChange to realtime and back shortly
- Leaving and rejoinging the world
- Restarting the world

### Expected behavior

No Performance impact from just defocussing the world or disabling the probes.
Not getting "Stuck" 

### Resonite Version Number

Beta 2025.2.21.98

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Index (Was in Hybrid mode)

### Log Files

Ill provide some proper logs tomorrow!

### Additional Context

A quick Video about the issue being Stuck and causing a high load:

https://youtu.be/CMlfcCeT3C0

### Reporters

Readun, Firefly, Zahndy

**Comment by Readun** [comment]
The Log File:

[READUN-PC - 2025.2.26.174 - 2025-02-26 19_19_53.log](https://github.com/user-attachments/files/18991183/READUN-PC.-.2025.2.26.174.-.2025-02-26.19_19_53.log)

And a Video of the process what I did, the Logfile and video are from the same try.

Another point I found out:

- The Reflection probe only needs to be disabled to cause those issues.
- Changing the ProbeType to Baked wont help, it needs to be turned to Realtime once, to fix the Reflection Probe.

https://youtu.be/BmbjabmG84c

**Comment by Frooxius** [comment]
Do you know if the probe keeps re-rendering itself constantly when this happens?

**Comment by Frooxius** [comment]
Can you provide a replication world?

**Comment by Readun** [comment]
I could try after mmc, but so far its been in 2 different worlds, where the sun rotation is driving the OnChange. Been happening to all of the probes so far that I tried to setup with OnChange.
(I probabstick to realtime for the mmc submission for now)

**Comment by Readun** [comment]
@Frooxius I setup a world with the sky system and reflection probes I had from the Video.
resrec:///U-Readun/R-88e8505c-8529-48b7-a47e-80f8446b52e4
I hope this should be accessable?

**Comment by shiftyscales** [comment]
The above world is accessible, yes. Thank you.

**Comment by Frooxius** [comment]
Should be fixed in 2025.3.17.1373! Thanks for report!

**Comment by Readun** [comment]
I just tested it briefly by leaving and coming back into the world + Disabling the slots and reenabling them.
The issue is still there in "Beta 2025.3.18.23" @Frooxius :/
I cant reopen the issue aswell.

**Comment by Frooxius** [comment]
Thanks, I've reopened this. It's seems like  there's another thing going on.

**Comment by Frooxius** [comment]
Okay, I'm pretty confident this is fixed now in 2025.3.25.1348!

This turned out to be a Unity bug, where if probe was disabled while it was doing a time-sliced render, it would become "stuck" forever and things would explode.

Thanks for report!

**Comment by Readun** [comment]
@Frooxius can this issue be reopened?

**Comment by Frooxius** [comment]
Does the original report replicate the issue? Or do you need different steps?

It might be better to make a new issue if it's the latter.

**Comment by Frooxius** [comment]
Actually I'd just recommend making a new issue anywyays, since there is a different problem now and it might even not be related, but a pre-existing issue.

**Comment by Readun** [comment]
> Does the original report replicate the issue? Or do you need different steps?
> 
> It might be better to make a new issue if it's the latter.

Its still the same steps, only that is has no effect now.
The OnChange acts as being stuck / baked and doesnt update at all now when the tracked Value changes. (Very noticeable when the world starts in Daytime and it gets night, the area of the reflection probe stays brighter than the rest.
