### ISSUE TITLE
Pressing Setup From Children twice on DynamicBoneChain breaks the component.

### ISSUE THREAD

**Issue by ko-tengu** [Yellow-Dog-Man/Resonite-Issues#3961]
### Describe the bug?

While setting up a DynamicBoneChain if you press the Setup From Children buttons while bones are already assigned the component disables itself.

### To Reproduce

Press the button twice

### Expected behavior

For the component to continue working.

### Screenshots

https://github.com/user-attachments/assets/6121b5f5-9ad8-434b-8c32-a44d8f34687b

### Resonite Version Number

Beta 2025.3.18.23

### What Platforms does this occur on?

Windows

### Log Files

[BUFU - 2025.3.18.23 - 2025-03-20 04_56_28.log](https://github.com/user-attachments/files/19362089/BUFU.-.2025.3.18.23.-.2025-03-20.04_56_28.log)

**Comment by Frooxius** [comment]
This should be fixed in 2025.3.25.1348. However I couldn't test this definitely since there's no replication item.

**Comment by ko-tengu** [comment]
It is not fixed, sorry for not uploading the replication item, I had made one and then forgot to export it. Simply push the Setup From Children button and it will stop wiggling and throw the same exception. 

[Sphere.zip](https://github.com/user-attachments/files/19458520/Sphere.zip)

[BUFU - 2025.3.25.1348 - 2025-03-25 20_13_53.log](https://github.com/user-attachments/files/19458539/BUFU.-.2025.3.25.1348.-.2025-03-25.20_13_53.log)

Should be the exception at line 1286, with a debug inserted at 1336 by me hitting f3 immediately after clicking the button.
