### ISSUE TITLE
Headless does not start due to missing assemblies

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#4073]
### Describe the issue.

When attempting to start the headless on the Awwdio prerelease, the headless fails to start due to missing assemblies.

This happens both on Linux and Windows

### To Reproduce

Switch to prerelease branch on Steam

Attempt to run headless

Observe headless crashing due to missing assemblies

### Expected behavior

Headless to start and behave normally

### Resonite Version Number

Beta 2025.4.7.1381 (Prerelease)

### What Platforms does this occur on?

Windows, Linux

### Log Files

[pluto - 2025.4.7.1381 - 2025-04-08 12_13_26.log](https://github.com/user-attachments/files/19640608/pluto.-.2025.4.7.1381.-.2025-04-08.12_13_26.log)

[WINSERVER - 2025.4.7.1381 - 2025-04-08 12_13_46.log](https://github.com/user-attachments/files/19640610/WINSERVER.-.2025.4.7.1381.-.2025-04-08.12_13_46.log)

### Reporters

bredo
Grand (grand__)
gamethecupdog

**Comment by GrandtheUK** [comment]
Have also run into this issue with my own headless grabbed with steamcmd. Mentioned it on the discussion on the pre-release. Here's my log

[Awwdio.log](https://github.com/user-attachments/files/19640620/Awwdio.log)

**Comment by Frooxius** [comment]
Fixed this in 2025.4.8.119! Thanks!

**Comment by bredo228** [comment]
This seems fixed on Windows, but Linux still crashes.

Will create a follow up issue

**Comment by GrandtheUK** [comment]
same here. headless still crashes on linux on my server

**Comment by bredo228** [comment]
Follow up issue created: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/4084
