### ISSUE TITLE
Issues starting headless on Linux

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#4084]
### Describe the issue.

Following https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/4073, the headless now works under Windows with the Awwdio prerelease.

Linux is still broken however, giving a similar error to before.

### To Reproduce

Switch to prerelease branch on a Linux headless

Try to start the headless, observe it crashes.

### Expected behavior

Headless to start and work normally.

### Resonite Version Number

Beta 2025.4.8.119 (Prerelease)

### What Platforms does this occur on?

Linux

### Log Files

[pluto - 2025.4.8.119 - 2025-04-08 14_15_47.log](https://github.com/user-attachments/files/19641530/pluto.-.2025.4.8.119.-.2025-04-08.14_15_47.log)

### Reporters

bredo

**Comment by Frooxius** [comment]
This should be fixed in 2025.4.8.1280. 

Can you give that build a try and see if anything else comes up?

**Comment by bredo228** [comment]
Looks like this fix has resolved the library not loading issue

However, the headless still crashes on Linux

[pluto - 2025.4.8.1280 - 2025-04-09 09_44_53.log](https://github.com/user-attachments/files/19657340/pluto.-.2025.4.8.1280.-.2025-04-09.09_44_53.log)

**Comment by Frooxius** [comment]
Thanks! Looking into this now!

**Comment by Frooxius** [comment]
Okay try 2025.4.8.1393!

**Comment by bredo228** [comment]
There's a different error now!

[pluto - 2025.4.8.1393 - 2025-04-09 11_23_11.log](https://github.com/user-attachments/files/19658118/pluto.-.2025.4.8.1393.-.2025-04-09.11_23_11.log)

**Comment by Frooxius** [comment]
WHA. It's the OVRLipSync now.

I need to setup a Linux machine/VM.

**Comment by Frooxius** [comment]
Okay try 2025.4.8.1409? x3

**Comment by bredo228** [comment]
Steam doesn't appear to like me updating my install right now, trying to resolve this.

**Comment by bredo228** [comment]
Tried a fresh install of the prerelease branch on a couple different machines - Steam appears to be still downloading build 2025.4.8.1393

**Comment by FoxoBread** [comment]
> Tried a fresh install of the prerelease branch on a couple different machines - Steam appears to be still downloading build 2025.4.8.1393

Steam hasn't propagated the depot for 1409 yet. Can't get it myself either.

**Comment by Frooxius** [comment]
I'm re-pushing this again in case.

**Comment by FoxoBread** [comment]
All is well, Headless starts now on build `Beta 2025.4.8.1409`

**Comment by Frooxius** [comment]
Oooh awesome! Thank you for confirmation! I'm going to close this one now!

**Comment by bredo228** [comment]
Looks like that's done the trick, headless starts as normal now.
