### ISSUE TITLE
Crackling audio when engine is put under load and/or stuttering

### ISSUE THREAD

**Issue by ohzee00** [Yellow-Dog-Man/Resonite-Issues#4233]
### Describe the issue.

When the engine is under load from anything happening in a session, the audio seems to crackle from any sounds currently playing with a increase of underruns happening at the same time.

Adjusting the various audio quality settings did not do much to change the frequency of audio crackling.

While it is inconsistent at times, opening a user inspector/component heavy slot, baking a reflection probe, using heavy particle systems and similar methods seem to cause the crackles.

### To Reproduce

Open this world via copy and paste, inside you can see various ways to stutter your game:
resrec:///U-ohzee/R-3efb25f4-3d1f-4eb2-8fca-9e180c29c190
1. Make sure you hear the music in the center
2. Rebake reflection probe, see if any crackles happen
3. Select Root or your own userroot and check if crackles happen
4. Grab particle gun and shoot at the field of very mesh dense Aegis' (Aegisi?), see if any crackles happen

### Expected behavior

Audio crackles should not happen overall, even in processing heavy scenes.

### Screenshots

Imgur links because file limit, make sure to unmute!

Replication case video:
https://imgur.com/VnlCyIS

Testing with the various audio quality settings:
https://imgur.com/S19oQsw

### Resonite Version Number

Beta 2025.5.2.1032

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-V75BHJO - 2025.5.2.1032 - 2025-05-03 04_19_37.log](https://github.com/user-attachments/files/20022616/DESKTOP-V75BHJO.-.2025.5.2.1032.-.2025-05-03.04_19_37.log)

### Additional Context

This is a hard issue to test because even the methods I tried above aren't consistent, sometimes it happens sometimes it doesn't. I even had them happen when just alt tabbed in a empty session with a single playing audio clip.

They are pretty bad though compared to release and given how much the game can stutter currently, it happening can be near constant.

### Reporters

Ohzee
bluecyro
KarasuTengu

**Comment by ko-tengu** [comment]
It's honestly closer to entire audio dropouts, which is something that Resonite has normally been pretty good about handling. Anytime I play with an inspector or open the World Browser the game will stop playing audio until it's recovered from whatever it was loading.

**Comment by epicEaston197** [comment]
> It's honestly closer to entire audio dropouts, which is something that Resonite has normally been pretty good about handling. Anytime I play with an inspector or open the World Browser the game will stop playing audio until it's recovered from whatever it was loading.

I think that might be because since the audio listener is not a component it is not subjected to Froox engine updates so if the game isn't responsive then the component isn't responsive?

I could be completely wrong but that's what I'm suspecting here is that the component isn't receiving updates due to the client hanging

**Comment by Frooxius** [comment]
This is actually a known issue, just one that I haven't addressed yet. 

We're using TPL to do the heavy multi-threaded processing. However by default we can't control the thread priority with this, so it runs with everything else, so if there's a bottleneck, the audio tasks end up getting delayed.

I'll be replacing it with a custom task scheduler with a very high thread priority, so it gets priority over everything else.

**Comment by Frooxius** [comment]
This should be fixed in 2025.5.5.1385! Or at at least significantly mitigated. The Awwdio now uses its own thread scheduler with high priority.

Thanks for report!

**Comment by Dusty-Sprinkles** [comment]
Are there any plans for further mitigations? I feel like there's still a significant (though definitely less) amount of popping in audio currently that could be worth trying to eliminate if possible (though idk if it would be better in a different issue)

**Comment by BlueCyro** [comment]
> This should be fixed in 2025.5.5.1385! Or at at least significantly mitigated. The Awwdio now uses its own thread scheduler with high priority.
> 
> Thanks for report!

I'm currently testing now and I still get significantly more crackling than the previous audio system. Starting Resonite yields very crackly audio as things start up for the first time (does not happen whatsoever on main).

After startup, it feels as though the crackling is maybe reduced somewhat? But if it is, it's enough that I can't really tell the difference. It's still significantly more than the main build to the point that I'd consider this issue unsolved.

**Comment by ohzee00** [comment]
This is a improvement! It seems to be a fair bit less now, I did a video of the same replication case and while there is still some crackles the really bad one from the reflection probe are almost completely gone.

It does seem to passively just _happen_ and I would encourage others to see if they can narrow it down at all/if it happens to them but yeah.

(There is a discord ping in the audio)
https://imgur.com/d9kGpfD

**Comment by BlueCyro** [comment]
> Can you record video please? And watch what happens to the underruns?

https://github.com/user-attachments/assets/7204ee18-adb9-42da-820e-0f9c83657744

Apologies for the crunchy quality, it should still be readable, but you can see how it behaves under both external system load, and some in-game load from doing stuff like opening my avatar.

**Comment by Frooxius** [comment]
Does increasing the buffer size to 2048 help?

**Comment by BlueCyro** [comment]
> Does increasing the buffer size to 2048 help?

It helps reduce the crackling quite a bit, but it still unfortunately happens under load whether it be in-game load or external load.

Also interestingly, makes waveforms lower framerate and visemes less expressive. Though those are separate issues so I won't discuss them here, but figured it was worth mentioning nonetheless.

**Comment by Frooxius** [comment]
Hmm... the only solution I see is making the threads realtime. It's a bit tricky issue, because if the threads are getting starved, we can only really increase their priority. 

The visemess & waveforms lower framerate is expected - the threads are getting to run a lot less, so these things end up updating at lower rate.

**Comment by BlueCyro** [comment]
> Hmm... the only solution I see is making the threads realtime. It's a bit tricky issue, because if the threads are getting starved, we can only really increase their priority.
> 
> The visemess & waveforms lower framerate is expected - the threads are getting to run a lot less, so these things end up updating at lower rate.

I believe having audio threads realtime is what's typically done to ensure that audio doesn't crackle like this. For example; pipewire and it's sub processes on linux run with an extremely negative 'nice' value (super duper extremely high priority) that is essentially realtime to ensure that audio processing happens correctly when piping audio/video around.

**Comment by Frooxius** [comment]
@BlueCyro That's kinda what we're using right now, it's set to highest possible priority.

There's also special "Realtime" mode, which is essentially "This thread will run until it says it doesn't want to anymore", which... it's a fair bit dangerous, so it's not used as much.

I checked and .NET doesn't actually expose that mode.

**Comment by BlueCyro** [comment]
It appears that my crackling issue is due to Linux [not respecting thread priority](https://github.com/dotnet/runtime/issues/91165) properly under mono/dotnet.

**Comment by Frooxius** [comment]
This should be fixed in 2025.5.6.1338 now! I've had @BlueCyro test the change on an internal build (I wanted to test the approach before finishing its implementation) so I'm confident to close this, but let me know if there's still issues. 

Thanks for all the reports!

**Comment by GrayBoltWolf** [comment]
@Frooxius @BlueCyro  I think this one needs to be revisited. With the new audio system both Ralinesh and I have had nonstop issues with crackling and audio cutting out as described in this report. 

Resonite is almost unusable now, any session with more than a few people you only hear about 50% of conversations, even in a private session audio drops about once a minute. My system running a 7950X3D fares a bit better, but Ralinesh has a 12700K, not a slow CPU by any measure. 

We've tried cranking the audio buffer settings, changing CPU thread priorities, power profiles, etc all in vain.

Is it possible to enable the old audio system manually? Even under full CPU load (transcoding video in the background) Resonite wouldn't drop at all, it was perfect.

**Comment by Frooxius** [comment]
@GrayBoltWolf Can you make a new report please? The issues within this one were addressed already, so there's probably another cause that can be affecting some machines / setups (there have been a number of causes of crackles and drops out).

We need a clean report - including the OS info, logs and all that stuff - for this issue I'd also provide screenshots/video of the Debug on "Worlds" tab that shows the under flows.

It's not possible to enable old audio system - it doesn't exist anymore, the system has been reworked.
