### ISSUE TITLE
Face Tracking Does Not Initialize on Resonite Start Up Using a Vive Pro Eye

### ISSUE THREAD

**Issue by Charizmare** [Yellow-Dog-Man/Resonite-Issues#4417]
### Describe the issue.

When starting SR_runtime then Resonite, Resonite does not hook into SR_runtime (system tray visual goes from orange to green and eyes and mouth track in game). In game, the eye's position is then defaultly driven by the Eye Manager and the mouth only moves using the avatar's visemes.

I also started Resonite first instead of SR_runtime and Resonite did not automatically start SR_runtime.

### To Reproduce

1. Start SR_runtime
2. Start Resonite
3. Resonite should hook into SR_runtime (system tray visual goes from orange to green and eyes and mouth track in game) but this does not happen. Instead, the eye manager is used for automatic eye movement and mouth tracking does not work.

### Expected behavior

SR_runtime system tray visual goes from orange to green and eyes and face track/move in game.

### Resonite Version Number

Beta 2025.5.20.1307

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive Pro Eye

### Log Files

[DESKTOP-LOEURJJ - 2025.5.20.1307 - 2025-05-20 18_20_02.log](https://github.com/user-attachments/files/20357583/DESKTOP-LOEURJJ.-.2025.5.20.1307.-.2025-05-20.18_20_02.log)

### Additional Context

Here is a video for context:
https://youtu.be/SCOVpmN9E4w

### Reporters

Charizmare

**Comment by Frooxius** [comment]
I've pushed a build 2025.5.20.1307 with extra logging. Can you re-test with that one please and send me logs?

**Comment by Charizmare** [comment]
Here's a fresh log, straight from my computer.

[DESKTOP-LOEURJJ - 2025.5.20.1370 - 2025-05-20 19_01_32.log](https://github.com/user-attachments/files/20357772/DESKTOP-LOEURJJ.-.2025.5.20.1370.-.2025-05-20.19_01_32.log)

**Comment by Frooxius** [comment]
Hmm this is peculiar. I've pushed build 2025.5.20.1406 can you test with that one please and send me log?

**Comment by Charizmare** [comment]
The same issue seems to still be occurring (SR_runtime system tray visual not turning green when active and the eyes and mouth are not tracking). Here's a new log file:

[DESKTOP-LOEURJJ - 2025.5.20.1370 - 2025-05-20 19_01_32.log](https://github.com/user-attachments/files/20358109/DESKTOP-LOEURJJ.-.2025.5.20.1370.-.2025-05-20.19_01_32.log)

**Comment by Charizmare** [comment]
Unfortunately, the issue is still occurring. Here is another log file:

[DESKTOP-LOEURJJ - 2025.5.20.1370 - 2025-05-20 19_01_32.log](https://github.com/user-attachments/files/20358345/DESKTOP-LOEURJJ.-.2025.5.20.1370.-.2025-05-20.19_01_32.log)

**Comment by Charizmare** [comment]
Here is what happened this time:

When I started Resonite with SR_runtime running before starting Resonite, it initialized only the mouth (SR_runtime system tray visual had the mouth green while the eyes remained orange). In game, only the mouth was tracked and could be moved. The eyes still moved only through the eye manager.

When I started Resonite without running SR_runtime before, it asked to run it. Then it asked a second time to run. It did not start SR_runtime a second time after I pressed yes on the User Account Control prompt. In game, only the mouth was tracked and could be moved. The eyes still moved only through the eye manager.

Here is also my latest log file:

[DESKTOP-LOEURJJ - 2025.5.21.8 - 2025-05-20 20_46_49.log](https://github.com/user-attachments/files/20358475/DESKTOP-LOEURJJ.-.2025.5.21.8.-.2025-05-20.20_46_49.log)

**Comment by Frooxius** [comment]
@Charizmare So if I understand correctly, eye tracking just doesn't work in either case, while face tracking does?

**Comment by Charizmare** [comment]
Correct.

**Comment by Frooxius** [comment]
Can you give 2025.5.21.266 a try please?

**Comment by Charizmare** [comment]
Here are my results when testing with this build:

When I started Resonite with SR_runtime already running both the eyes and mouth tracked in game. The system tray visual was also fully green. I tried this a second and a third time and it had the same results as the first.

When I started Resonite without SR_runtime running already it was inconsistent on what it had working.
The first time only the eyes working in game with the system tray visual only having the eyes green while the mouth was orange.
The second time had both the eyes and mouth on the system tray visual green though neither the eyes or mouth tracked in game.
The third time had the same results as the first (only the eyes were tracked in game).
The forth time had both the eyes and the mouth tracking in game.
The fifth time had the same results as the first and the third (only the eyes were tracked in game).

Here are logs for both SR_runtime running before Resonite runs and when Resonite runs SR_runtime:

Running SR_runtime before Resonite:

[DESKTOP-LOEURJJ - (SR_Runtime Running Before Reso) 2025.5.21.266 - 2025-05-21 01_15_43.log](https://github.com/user-attachments/files/20360813/DESKTOP-LOEURJJ.-.SR_Runtime.Running.Before.Reso.2025.5.21.266.-.2025-05-21.01_15_43.log)

Resonite running SR_runtime on its start up:

[DESKTOP-LOEURJJ - (Resonite Starting SR_Runtime) 2025.5.21.266 - 2025-05-21 01_15_43.log](https://github.com/user-attachments/files/20360818/DESKTOP-LOEURJJ.-.Resonite.Starting.SR_Runtime.2025.5.21.266.-.2025-05-21.01_15_43.log)

**Comment by Frooxius** [comment]
Do you have a log from when only one of the two was working? 

In both logs you provided it seems that both eye & lip tracking has initialized. 

From my understand is that sometimes lip tracking does not initialize?

**Comment by Charizmare** [comment]
Sometimes when Resonite starts SR_runtime (SR_runtime was not running before Resonite) the mouth would only work, the eyes would only work or one time out of five tests both of them worked.

I unfortunately will be away from my desk for the rest of the day but I will provide a log will only one of them working as soon as I can.

**Comment by Frooxius** [comment]
@Charizmare Do you have any update on this and logs?

Right now this is the only thing blocking the release and I currently don't have access to the HW to test this on my own.

**Comment by Charizmare** [comment]
My apologies, here's a log where only the eyes were tracking in game and the mouth wasn't. @Frooxius 

SR_runtime's system tray icon looked like this:

![Image](https://github.com/user-attachments/assets/1cf9591c-cc2f-4078-8fb2-6ec5a8c22663)

[DESKTOP-LOEURJJ - 2025.5.21.266 - 2025-05-21 01_43_13.log](https://github.com/user-attachments/files/20397606/DESKTOP-LOEURJJ.-.2025.5.21.266.-.2025-05-21.01_43_13.log)

**Comment by Frooxius** [comment]
@Charizmare Thanks for the log! I've added some additional diagnostics in 2025.5.22.1090. Would you be able to replicate this issue with that one please?

**Comment by Charizmare** [comment]
Testing with this build resulted in the same issue as the last build. Here's the log from that test:

[DESKTOP-LOEURJJ - 2025.5.22.1090 - 2025-05-22 14_32_13.log](https://github.com/user-attachments/files/20398605/DESKTOP-LOEURJJ.-.2025.5.22.1090.-.2025-05-22.14_32_13.log)

**Comment by Frooxius** [comment]
@Charizmare Thanks for the log!

Hmm... I have a hunch on what it might be. Can you test 2025.5.22.1119 build please? It might have a potential fix.

**Comment by Charizmare** [comment]
After testing this build at least twice I found that both eye and mouth tracking work. The SR_runtime system tray icon was fully green as well!

I also tested having SR_runtime run before Resonite just to make sure that was working still and I can confirm that this case worked as well!

**Comment by Frooxius** [comment]
@Charizmare Awesome! Thank you so much! Closing this!
