### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by kulzae** [Yellow-Dog-Man/Resonite-Issues#5262]
### Describe the issue.

My other computer is unable to startup the game. the loading screen appears for a second before the entire program closes

### To Reproduce

This isnt happening on my desktop so I have no idea

### Expected behavior

Being able to start the game. This issue did not occur on 8.15.xxx

### Resonite Version Number

Beta 2025.8.16.646

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[VM10 - 2025.8.16.646 - 2025-08-16 13_49_52.log](https://github.com/user-attachments/files/21815553/VM10.-.2025.8.16.646.-.2025-08-16.13_49_52.log)

**Comment by kulzae** [comment]
Also occuring on my headless now. literally had the headless running. closed it. started it again and now it wont start

**Comment by Muppeq** [comment]
I just tried to install and run the prerelease on my small laptop, I think I have the same crash, the error in my log looks to be the same one.


[DESKTOP-0HLEJ4K - 2025.8.16.646 - 2025-08-16 20_15_14.log](https://github.com/user-attachments/files/21815669/DESKTOP-0HLEJ4K.-.2025.8.16.646.-.2025-08-16.20_15_14.log)

**Comment by Muppeq** [comment]
I could fix this crash by verifying the steam installation.

I wanted to test out my new changes in the de.json locale translation, and already had my changed language file copied into the Locale folder.

I ran steams 'Verify integrity of game files' to revert this change, and resonite starts now.

But now it even starts when I copy my changed de.json file back again into the Locale direcory, so I don't know if that caused the problem.

**Comment by Moonbasee** [comment]
headless is also crashing for me but its with a type exception

[2ed4b431e9d7 - 2025.8.16.646 - 2025-08-16 13_28_01.log](https://github.com/user-attachments/files/21817592/2ed4b431e9d7.-.2025.8.16.646.-.2025-08-16.13_28_01.log)

**Comment by Frooxius** [comment]
Fixed this on 2025.8.16.1300! Thanks for report!

**Comment by Moonbasee** [comment]
still wont start for me

[cd34cf0a8a5a - 2025.8.16.1300 - 2025-08-16 14_51_44.log](https://github.com/user-attachments/files/21818269/cd34cf0a8a5a.-.2025.8.16.1300.-.2025-08-16.14_51_44.log)

**Comment by Frooxius** [comment]
@Moonbasee Can you verify your installation please? It looks like the files are corrupted.

**Comment by Moonbasee** [comment]
It's a docker container that redownloads the game every time, nothing should be corrupt.

**Comment by Moonbasee** [comment]
oh shit i forgot about mods, one second
