### ISSUE TITLE
Audio can break and prevent closing Resonite

### ISSUE THREAD

**Issue by Krzeszny** [Yellow-Dog-Man/Resonite-Issues#5427]
### Describe the bug?

I joined many sessions (about 15) and on joining the last session, I stopped hearing audio. Even forcing the audio devices to refresh didn't fix it. I didn't try switching sessions.

I tried to exit resonite and it froze for several minutes on exiting.

Then I clicked the window to stop the frozen process, forced it to close and the window disappeared but it was still running according to Steam library.

Then I clicked STOP in Steam library and it finally quit for good.

### To Reproduce

Join too many sessions? I'm not sure.

### Reproduction Item/World

N/A

### Expected behavior

Audio doesn't break

### Resonite Version Number

2025.8.22.607

### What Platforms does this occur on?

Windows

### What headset if any do you use?

none

### Log Files

[DESKTOP-VHA2V7H - 2025.8.22.607 - 2025-08-25 06_48_12.log](https://github.com/user-attachments/files/21961807/DESKTOP-VHA2V7H.-.2025.8.22.607.-.2025-08-25.06_48_12.log)

### Reporters

@krzeszny

**Comment by Frooxius** [comment]
This should be fixed in 2026.2.19.620!

**Comment by Redd56** [comment]
so turns out this isnt fully fixed, just had an audio engine crash that occurred that caused this bug again. Sadly i was running modded so its not the cleanest logs known to man but to my knowledge none of my mods should touch the audio engine as they are all qol mods like custom inspectors and such
and restrinite so i can toggle my lasers
the only error refrencing awwdio i could find was at line 4456
log abruptly ends as i had to force kill the game


[reddspc - 2026.2.19.620 - 2026-02-20 14_57_20.log](https://github.com/user-attachments/files/25453899/reddspc.-.2026.2.19.620.-.2026-02-20.14_57_20.log)

**Comment by Frooxius** [comment]
Please make a new clean report.

**Comment by Redd56** [comment]
done #6457
