### ISSUE TITLE
Odd crash on certain avatars loading into worlds. 

### ISSUE THREAD

**Issue by liny-fox** [Yellow-Dog-Man/Resonite-Issues#592]
### Describe the bug?

Not too sure how to describe this other that as soon as certain avatars load into a headless server the world crashes.

### To Reproduce

Have someone with an affected AV load into it.

### Expected behavior

Not to crash the world

### Resonite Version Number

Beta 2023.11.8.335

### What Platforms does this occur on?

Linux

### Log Files

`Exception in decoding element: Element: ID1941B02, Type: FrooxEngine.WorkerBag`1[FrooxEngine.Component], World: The Red Lantern Inn (Lite), IsRemoved: False, Name: Components, Disposed: False
Element: ID1941702, Type: FrooxEngine.Slot, World: The Red Lantern Inn (Lite), IsRemoved: False, Slot name: Stream Control, T: [0; 0; 0], R: [0; 0; 0; 1], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
Element: ID2400, Type: FrooxEngine.Slot, World: The Red Lantern Inn (Lite), IsRemoved: False, Slot name: Root, T: [0; 0; 0], R: [0; 0; 0; 1], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
Element: ID0, Type: FrooxEngine.World, World: The Red Lantern Inn (Lite), IsRemoved: False
.
System.Exception: Error instantiating type: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Exception loading type FrooxEngine.TwitchInterface ---> System.TypeLoadException: Could not load type of field 'TwitchLib.Client.TwitchClient:OnMessageThrottled' (56) due to: Could not resolve type with token 01000014 from typeref (expected class 'TwitchLib.Communication.Events.OnMessageThrottledEventArgs' in assembly 'TwitchLib.Communication, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null') assembly:TwitchLib.Communication, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null type:TwitchLib.Communication.Events.OnMessageThrottledEventArgs member:(null)
  at (wrapper managed-to-native) System.RuntimeTypeHandle.type_is_assignable_from(System.Type,System.Type)
  at System.RuntimeTypeHandle.CanCastTo (System.RuntimeType type, System.RuntimeType target) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.IsAssignableFrom (System.Type c) [0x00020] in <d636f104d58046fd9b195699bcb1a744>:0
  at FrooxEngine.WorkerInitializer.IsValidField (System.Reflection.FieldInfo field, System.Type workerType) [0x00010] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer+<>c__DisplayClass31_0.<GatherWorkerFields>b__0 (System.Reflection.FieldInfo f) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at System.Linq.Enumerable+WhereArrayIterator`1[TSource].ToList () [0x00019] in <69ada62907b24213a012734531df1db1>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <69ada62907b24213a012734531df1db1>:0
  at FrooxEngine.WorkerInitializer.GatherWorkerFields (System.Type workerType, System.Collections.Generic.List`1[T] fields) [0x00058] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.Initialize (System.Type workerType) [0x0000c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.GetInitInfo (System.Type workerType) [0x0000f] in <6473191ffe0446be81b335dd5f434a48>:0
   --- End of inner exception stack trace ---
  at FrooxEngine.WorkerInitializer.GetInitInfo (System.Type workerType) [0x00037] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.GetInitInfo (FrooxEngine.IWorker worker) [0x00006] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Worker..ctor () [0x00012] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.ComponentBase`1[C]..ctor () [0x0000c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Component..ctor () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.TwitchInterface..ctor () [0x00016] in <6473191ffe0446be81b335dd5f434a48>:0
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <d636f104d58046fd9b195699bcb1a744>:0
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x0001a] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00020] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at FrooxEngine.WorkerManager.Instantiate (System.Type type) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Exception loading type FrooxEngine.TwitchInterface ---> System.TypeLoadException: Could not load type of field 'TwitchLib.Client.TwitchClient:OnMessageThrottled' (56) due to: Could not resolve type with token 01000014 from typeref (expected class 'TwitchLib.Communication.Events.OnMessageThrottledEventArgs' in assembly 'TwitchLib.Communication, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null') assembly:TwitchLib.Communication, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null type:TwitchLib.Communication.Events.OnMessageThrottledEventArgs member:(null)
  at (wrapper managed-to-native) System.RuntimeTypeHandle.type_is_assignable_from(System.Type,System.Type)
  at System.RuntimeTypeHandle.CanCastTo (System.RuntimeType type, System.RuntimeType target) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.IsAssignableFrom (System.Type c) [0x00020] in <d636f104d58046fd9b195699bcb1a744>:0
  at FrooxEngine.WorkerInitializer.IsValidField (System.Reflection.FieldInfo field, System.Type workerType) [0x00010] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer+<>c__DisplayClass31_0.<GatherWorkerFields>b__0 (System.Reflection.FieldInfo f) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at System.Linq.Enumerable+WhereArrayIterator`1[TSource].ToList () [0x00019] in <69ada62907b24213a012734531df1db1>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <69ada62907b24213a012734531df1db1>:0
  at FrooxEngine.WorkerInitializer.GatherWorkerFields (System.Type workerType, System.Collections.Generic.List`1[T] fields) [0x00058] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.Initialize (System.Type workerType) [0x0000c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.GetInitInfo (System.Type workerType) [0x0000f] in <6473191ffe0446be81b335dd5f434a48>:0
   --- End of inner exception stack trace ---
  at FrooxEngine.WorkerInitializer.GetInitInfo (System.Type workerType) [0x00037] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.GetInitInfo (FrooxEngine.IWorker worker) [0x00006] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Worker..ctor () [0x00012] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.ComponentBase`1[C]..ctor () [0x0000c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Component..ctor () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.TwitchInterface..ctor () [0x00016] in <6473191ffe0446be81b335dd5f434a48>:0
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <d636f104d58046fd9b195699bcb1a744>:0
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x0001a] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00020] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at FrooxEngine.WorkerManager.Instantiate (System.Type type) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
   --- End of inner exception stack trace ---
  at FrooxEngine.WorkerManager.Instantiate (System.Type type) [0x00020] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerBag`1[W].DecodeElement (System.IO.BinaryReader reader) [0x00011] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncBagBase`2[K,T].InternalDecodeDelta (System.IO.BinaryReader reader, FrooxEngine.BinaryMessageBatch inboundMessage) [0x0001c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncElement.DecodeDelta (System.IO.BinaryReader reader, FrooxEngine.BinaryMessageBatch inboundMessage) [0x00025] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncController.DecodeBinaryMessage (System.Int32 recordIndex, FrooxEngine.BinaryMessageBatch message, System.Boolean isFull) [0x0002e] in <6473191ffe0446be81b335dd5f434a48>:0

  at System.Environment.get_StackTrace () [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at Elements.Core.UniLog.Error (System.String message, System.Boolean stackTrace) [0x00000] in <3a9597271a1e49c581cf05318b6ddd23>:0
  at FrooxEngine.SyncController.DecodeBinaryMessage (System.Int32 recordIndex, FrooxEngine.BinaryMessageBatch message, System.Boolean isFull) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncController.DecodeDeltaMessage (System.Int32 recordIndex, FrooxEngine.DeltaBatch batch) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.ApplyDataRecords (FrooxEngine.BinaryMessageBatch toProcess) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.ProcessMessage (FrooxEngine.SyncMessage msg, System.UInt64 lastDeltaSyncTime, System.Collections.Generic.List`1[T] controlMessagesToProcess) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.SyncLoop () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.RunThreadLoop (System.Action loop) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.<.ctor>b__78_2 () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ThreadHelper.ThreadStart () [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
Exception in processing message! Message: SyncMessage: Delta, SenderStateVersion: 30589, SenderSyncTick: 479, SenderUser: User ID50BFE00 (Alloc: 2) - UserName: Raxoron, UserId: U-Raxoron, MachineId: q57yoempq36ki8fds9pzwrf13ao5kq3gaq15gb3z5w3rcq6cqany, Role: Guest, Targets.Count: 0, DataRecordCount: 82326, DataBytes: 1016580, sender: FrooxEngine.LNL_Peer, user: User ID50BFE00 (Alloc: 2) - UserName: Raxoron, UserId: U-Raxoron, MachineId: q57yoempq36ki8fds9pzwrf13ao5kq3gaq15gb3z5w3rcq6cqany, Role: Guest, sender sync tick: 479, sender state version: 30589, confirmation time: , local sync tick: 12537, local state version: 30975
System.Exception: Error instantiating type: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Exception loading type FrooxEngine.TwitchInterface ---> System.TypeLoadException: Could not load type of field 'TwitchLib.Client.TwitchClient:OnMessageThrottled' (56) due to: Could not resolve type with token 01000014 from typeref (expected class 'TwitchLib.Communication.Events.OnMessageThrottledEventArgs' in assembly 'TwitchLib.Communication, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null') assembly:TwitchLib.Communication, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null type:TwitchLib.Communication.Events.OnMessageThrottledEventArgs member:(null)
  at (wrapper managed-to-native) System.RuntimeTypeHandle.type_is_assignable_from(System.Type,System.Type)
  at System.RuntimeTypeHandle.CanCastTo (System.RuntimeType type, System.RuntimeType target) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.IsAssignableFrom (System.Type c) [0x00020] in <d636f104d58046fd9b195699bcb1a744>:0
  at FrooxEngine.WorkerInitializer.IsValidField (System.Reflection.FieldInfo field, System.Type workerType) [0x00010] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer+<>c__DisplayClass31_0.<GatherWorkerFields>b__0 (System.Reflection.FieldInfo f) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at System.Linq.Enumerable+WhereArrayIterator`1[TSource].ToList () [0x00019] in <69ada62907b24213a012734531df1db1>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <69ada62907b24213a012734531df1db1>:0
  at FrooxEngine.WorkerInitializer.GatherWorkerFields (System.Type workerType, System.Collections.Generic.List`1[T] fields) [0x00058] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.Initialize (System.Type workerType) [0x0000c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.GetInitInfo (System.Type workerType) [0x0000f] in <6473191ffe0446be81b335dd5f434a48>:0
   --- End of inner exception stack trace ---
  at FrooxEngine.WorkerInitializer.GetInitInfo (System.Type workerType) [0x00037] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.GetInitInfo (FrooxEngine.IWorker worker) [0x00006] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Worker..ctor () [0x00012] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.ComponentBase`1[C]..ctor () [0x0000c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Component..ctor () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.TwitchInterface..ctor () [0x00016] in <6473191ffe0446be81b335dd5f434a48>:0
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <d636f104d58046fd9b195699bcb1a744>:0
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x0001a] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00020] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at FrooxEngine.WorkerManager.Instantiate (System.Type type) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Exception loading type FrooxEngine.TwitchInterface ---> System.TypeLoadException: Could not load type of field 'TwitchLib.Client.TwitchClient:OnMessageThrottled' (56) due to: Could not resolve type with token 01000014 from typeref (expected class 'TwitchLib.Communication.Events.OnMessageThrottledEventArgs' in assembly 'TwitchLib.Communication, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null') assembly:TwitchLib.Communication, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null type:TwitchLib.Communication.Events.OnMessageThrottledEventArgs member:(null)
  at (wrapper managed-to-native) System.RuntimeTypeHandle.type_is_assignable_from(System.Type,System.Type)
  at System.RuntimeTypeHandle.CanCastTo (System.RuntimeType type, System.RuntimeType target) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.IsAssignableFrom (System.Type c) [0x00020] in <d636f104d58046fd9b195699bcb1a744>:0
  at FrooxEngine.WorkerInitializer.IsValidField (System.Reflection.FieldInfo field, System.Type workerType) [0x00010] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer+<>c__DisplayClass31_0.<GatherWorkerFields>b__0 (System.Reflection.FieldInfo f) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at System.Linq.Enumerable+WhereArrayIterator`1[TSource].ToList () [0x00019] in <69ada62907b24213a012734531df1db1>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <69ada62907b24213a012734531df1db1>:0
  at FrooxEngine.WorkerInitializer.GatherWorkerFields (System.Type workerType, System.Collections.Generic.List`1[T] fields) [0x00058] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.Initialize (System.Type workerType) [0x0000c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.GetInitInfo (System.Type workerType) [0x0000f] in <6473191ffe0446be81b335dd5f434a48>:0
   --- End of inner exception stack trace ---
  at FrooxEngine.WorkerInitializer.GetInitInfo (System.Type workerType) [0x00037] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.GetInitInfo (FrooxEngine.IWorker worker) [0x00006] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Worker..ctor () [0x00012] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.ComponentBase`1[C]..ctor () [0x0000c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Component..ctor () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.TwitchInterface..ctor () [0x00016] in <6473191ffe0446be81b335dd5f434a48>:0
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <d636f104d58046fd9b195699bcb1a744>:0
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x0001a] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00020] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at FrooxEngine.WorkerManager.Instantiate (System.Type type) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
   --- End of inner exception stack trace ---
  at FrooxEngine.WorkerManager.Instantiate (System.Type type) [0x00020] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerBag`1[W].DecodeElement (System.IO.BinaryReader reader) [0x00011] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncBagBase`2[K,T].InternalDecodeDelta (System.IO.BinaryReader reader, FrooxEngine.BinaryMessageBatch inboundMessage) [0x0001c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncElement.DecodeDelta (System.IO.BinaryReader reader, FrooxEngine.BinaryMessageBatch inboundMessage) [0x00025] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncController.DecodeBinaryMessage (System.Int32 recordIndex, FrooxEngine.BinaryMessageBatch message, System.Boolean isFull) [0x0006e] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncController.DecodeDeltaMessage (System.Int32 recordIndex, FrooxEngine.DeltaBatch batch) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.ApplyDataRecords (FrooxEngine.BinaryMessageBatch toProcess) [0x0004c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.ProcessMessage (FrooxEngine.SyncMessage msg, System.UInt64 lastDeltaSyncTime, System.Collections.Generic.List`1[T] controlMessagesToProcess) [0x000b6] in <6473191ffe0446be81b335dd5f434a48>:0

  at System.Environment.get_StackTrace () [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at Elements.Core.UniLog.Error (System.String message, System.Boolean stackTrace) [0x00000] in <3a9597271a1e49c581cf05318b6ddd23>:0
  at FrooxEngine.Session.ProcessMessage (FrooxEngine.SyncMessage msg, System.UInt64 lastDeltaSyncTime, System.Collections.Generic.List`1[T] controlMessagesToProcess) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.SyncLoop () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.RunThreadLoop (System.Action loop) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.<.ctor>b__78_2 () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ThreadHelper.ThreadStart () [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
Exception in running thread loop System.Action:

System.Exception: Error instantiating type: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Exception loading type FrooxEngine.TwitchInterface ---> System.TypeLoadException: Could not load type of field 'TwitchLib.Client.TwitchClient:OnMessageThrottled' (56) due to: Could not resolve type with token 01000014 from typeref (expected class 'TwitchLib.Communication.Events.OnMessageThrottledEventArgs' in assembly 'TwitchLib.Communication, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null') assembly:TwitchLib.Communication, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null type:TwitchLib.Communication.Events.OnMessageThrottledEventArgs member:(null)
  at (wrapper managed-to-native) System.RuntimeTypeHandle.type_is_assignable_from(System.Type,System.Type)
  at System.RuntimeTypeHandle.CanCastTo (System.RuntimeType type, System.RuntimeType target) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.IsAssignableFrom (System.Type c) [0x00020] in <d636f104d58046fd9b195699bcb1a744>:0
  at FrooxEngine.WorkerInitializer.IsValidField (System.Reflection.FieldInfo field, System.Type workerType) [0x00010] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer+<>c__DisplayClass31_0.<GatherWorkerFields>b__0 (System.Reflection.FieldInfo f) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at System.Linq.Enumerable+WhereArrayIterator`1[TSource].ToList () [0x00019] in <69ada62907b24213a012734531df1db1>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <69ada62907b24213a012734531df1db1>:0
  at FrooxEngine.WorkerInitializer.GatherWorkerFields (System.Type workerType, System.Collections.Generic.List`1[T] fields) [0x00058] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.Initialize (System.Type workerType) [0x0000c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.GetInitInfo (System.Type workerType) [0x0000f] in <6473191ffe0446be81b335dd5f434a48>:0
   --- End of inner exception stack trace ---
  at FrooxEngine.WorkerInitializer.GetInitInfo (System.Type workerType) [0x00037] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.GetInitInfo (FrooxEngine.IWorker worker) [0x00006] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Worker..ctor () [0x00012] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.ComponentBase`1[C]..ctor () [0x0000c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Component..ctor () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.TwitchInterface..ctor () [0x00016] in <6473191ffe0446be81b335dd5f434a48>:0
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <d636f104d58046fd9b195699bcb1a744>:0
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x0001a] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00020] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at FrooxEngine.WorkerManager.Instantiate (System.Type type) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Exception loading type FrooxEngine.TwitchInterface ---> System.TypeLoadException: Could not load type of field 'TwitchLib.Client.TwitchClient:OnMessageThrottled' (56) due to: Could not resolve type with token 01000014 from typeref (expected class 'TwitchLib.Communication.Events.OnMessageThrottledEventArgs' in assembly 'TwitchLib.Communication, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null') assembly:TwitchLib.Communication, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null type:TwitchLib.Communication.Events.OnMessageThrottledEventArgs member:(null)
  at (wrapper managed-to-native) System.RuntimeTypeHandle.type_is_assignable_from(System.Type,System.Type)
  at System.RuntimeTypeHandle.CanCastTo (System.RuntimeType type, System.RuntimeType target) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.IsAssignableFrom (System.Type c) [0x00020] in <d636f104d58046fd9b195699bcb1a744>:0
  at FrooxEngine.WorkerInitializer.IsValidField (System.Reflection.FieldInfo field, System.Type workerType) [0x00010] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer+<>c__DisplayClass31_0.<GatherWorkerFields>b__0 (System.Reflection.FieldInfo f) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at System.Linq.Enumerable+WhereArrayIterator`1[TSource].ToList () [0x00019] in <69ada62907b24213a012734531df1db1>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <69ada62907b24213a012734531df1db1>:0
  at FrooxEngine.WorkerInitializer.GatherWorkerFields (System.Type workerType, System.Collections.Generic.List`1[T] fields) [0x00058] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.Initialize (System.Type workerType) [0x0000c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.GetInitInfo (System.Type workerType) [0x0000f] in <6473191ffe0446be81b335dd5f434a48>:0
   --- End of inner exception stack trace ---
  at FrooxEngine.WorkerInitializer.GetInitInfo (System.Type workerType) [0x00037] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorkerInitializer.GetInitInfo (FrooxEngine.IWorker worker) [0x00006] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Worker..ctor () [0x00012] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.ComponentBase`1[C]..ctor () [0x0000c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Component..ctor () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.TwitchInterface..ctor () [0x00016] in <6473191ffe0446be81b335dd5f434a48>:0
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <d636f104d58046fd9b195699bcb1a744>:0
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x0001a] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00020] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at FrooxEngine.WorkerManager.Instantiate (System.Type type) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
   --- End of inner exception stack trace ---
  at FrooxEngine.Session.ProcessMessage (FrooxEngine.SyncMessage msg, System.UInt64 lastDeltaSyncTime, System.Collections.Generic.List`1[T] controlMessagesToProcess) [0x0042d] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.SyncLoop () [0x000d1] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.RunThreadLoop (System.Action loop) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0

  at System.Environment.get_StackTrace () [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at Elements.Core.UniLog.Error (System.String message, System.Boolean stackTrace) [0x00000] in <3a9597271a1e49c581cf05318b6ddd23>:0
  at FrooxEngine.Session.RunThreadLoop (System.Action loop) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Session.<.ctor>b__78_2 () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ThreadHelper.ThreadStart () [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
Exception when running OnBeforeSaveStart Action: System.Action
System.Exception: Modifications from a non-locking thread are disallowed! Current lock: DataModel
  at FrooxEngine.ConnectorManager.ThreadCheck () [0x00026] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncElement.BeginModification (System.Boolean throwOnError) [0x00055] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncField`1[T].InternalSetValue (T& value, System.Boolean sync, System.Boolean change) [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.LinkBase`1[T].SetValue (Elements.Core.RefID& value, T prevTarget, System.Boolean sync, System.Boolean change) [0x0003c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.LinkBase`1[T].InternalSetValue (Elements.Core.RefID& value, System.Boolean sync, System.Boolean change) [0x00008] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncField`1[T].set_Value (T value) [0x0006e] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncRef`1[T].set_Value (Elements.Core.RefID value) [0x0000f] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.SyncRef`1[T].set_Target (T value) [0x00083] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.LinkBase`1[T].set_Target (T value) [0x0007c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.ProtoFlux.CoreNodes.FieldHookBase`1[T].DoStopDrive (FrooxEngine.ProtoFlux.FrooxEngineContext context) [0x0001c] in <6473191ffe0446be81b335dd5f434a48>:0
  at ProtoFlux.Runtimes.Execution.SyncOperationSequence`1[C].ExecuteSync (C context) [0x00031] in <0160e0d24ac5461f91747d41bc633de8>:0
  at ProtoFlux.Runtimes.Execution.ExecutionRuntime`1[C].ExecuteSequence (ProtoFlux.Core.ISyncOperation operation, C context) [0x00034] in <0160e0d24ac5461f91747d41bc633de8>:0
  at ProtoFlux.Runtimes.Execution.ExecutionRuntime`1[C].Execute (ProtoFlux.Core.ISyncOperation action, ProtoFlux.Runtimes.Execution.ExecutionContext context) [0x00012] in <0160e0d24ac5461f91747d41bc633de8>:0
  at ProtoFlux.Runtimes.Execution.Nodes.FrooxEngine.Slots.OnSaving+<>c__DisplayClass2_0.<ProxyAdded>b__1 (FrooxEngine.ProtoFlux.FrooxEngineContext c) [0x00000] in <1f58e9ca2349420a89df3bcced127003>:0
  at FrooxEngine.ProtoFlux.ProtoFluxNodeGroup.ExecuteImmediatelly (ProtoFlux.Core.NodeContextPath path, System.Action`1[T] callback) [0x00035] in <6473191ffe0446be81b335dd5f434a48>:0
  at ProtoFlux.Runtimes.Execution.Nodes.FrooxEngine.Slots.OnSaving+<>c__DisplayClass2_0.<ProxyAdded>b__0 () [0x00000] in <1f58e9ca2349420a89df3bcced127003>:0
  at FrooxEngine.SaveControl.StartSaving () [0x0001e] in <6473191ffe0446be81b335dd5f434a48>:0
Unhandled Exception when updating world: The Red Lantern Inn (Lite). State Running, Refresh Stage: RefreshBegin, Init State: Finished, SyncTick 12537, StateVersion: 30975
Dumped world state to:
System.Exception: Session has been disposed
  at FrooxEngine.Session.StopProcessing () [0x0003c] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.World.RefreshStep () [0x000d7] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.World.Refresh () [0x00073] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorldManager.UpdateStep () [0x004a3] in <6473191ffe0446be81b335dd5f434a48>:0

  at System.Environment.get_StackTrace () [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at Elements.Core.UniLog.Error (System.String message, System.Boolean stackTrace) [0x00000] in <3a9597271a1e49c581cf05318b6ddd23>:0
  at FrooxEngine.WorldManager.UpdateStep () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.WorldManager.RunUpdateLoop () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Engine.UpdateStep () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.Engine.RunUpdateLoop () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at FrooxEngine.StandaloneFrooxEngineRunner.UpdateLoop () [0x00000] in <6473191ffe0446be81b335dd5f434a48>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
  at System.Threading.ThreadHelper.ThreadStart () [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0
`

### Additional Context

Reproduced with USFN's Red Lantern Inn world. Unknown what on the AV causes the problem.

**Comment by ohzee00** [comment]
Please do give a full log file, not a snip of the exception, there is a lot of data it gives that can help narrow it down on the developers end.

**Comment by liny-fox** [comment]
I would but the session isnt a clean start of the headless, the world was opened with startWorldURL on my already running headless just to test and the snippet was acquired using the log command to have it spit out the snippet to the console on world crash. so the log is filled with everything else.

**Comment by Readun** [comment]
Was testing it with mine, as my Main Avatar crashes the worlds aswell, not the headless it looks like.
It seems to only affect Linux ones, my own Windows Server is not crashing (Tested it with Admin, Guest and Spectator).

**Comment by zahndy** [comment]
I found out that Headless branch uses 2.0.0.0 of TwitchLib.Communication while the normal client uses 1.0.6.0
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/662702/0482d245-47c1-469f-8d42-8ea8d2369288)

**Comment by RaithSphere** [comment]
yeah spotted the issue here

**Comment by RaithSphere** [comment]
> Was testing it with mine, as my Main Avatar crashes the worlds aswell, not the headless it looks like. It seems to only affect Linux ones, my own Windows Server is not crashing (Tested it with Admin, Guest and Spectator).

I just tested this now with a Windows Headless and also crashed

**Comment by RaithSphere** [comment]
Exception when Initializing channel RaithSphere:
System.TypeLoadException: Could not load type 'TwitchLib.Communication.Events.OnMessageThrottledEventArgs' from assembly 'TwitchLib.Communication, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at FrooxEngine.TwitchInterface.<Initialize>d__74.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at FrooxEngine.TwitchInterface.Initialize(String targetChannel)
   at FrooxEngine.TwitchInterface.<<OnChanges>b__73_0>d.MoveNext() in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Components\Integrations\Twitch\TwitchInterface.cs:line 0

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Elements.Core.UniLog.Error(String message, Boolean stackTrace) in C:\Workspace\Resonite\FrooxEngine\Elements.Core\UniLog.cs:line 59
   at FrooxEngine.TwitchInterface.<<OnChanges>b__73_0>d.MoveNext() in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Components\Integrations\Twitch\TwitchInterface.cs:line 0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at FrooxEngine.TwitchInterface.<OnChanges>b__73_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by RaithSphere** [comment]
Okay so the issue here looks like when the Headless is built TwitchLib.Communication.dll isn't copied over to the folder - I have mentioned this now

**Comment by RaithSphere** [comment]
Quick fix for now is to copy TwitchLib.Communication.dll from the Resonite_Data\Managed and put that into the directory of the headless

**Comment by Frooxius** [comment]
Should be fixed in 2023.11.11.1231! THanks!

**Comment by bontebok** [comment]
> TwitchLib.Communication.dll

Creator Jam crashed today due to this bug in 2023.11.11.1231, it appears there are two TwitchLib.Communication.dll's being distributed in the Linux headless.

$ cat Build.version
2023.11.11.1231

$ find . -name TwitchLib.Communication.dll
./Resonite_Data/Managed/TwitchLib.Communication.dll
./Headless/TwitchLib.Communication.dll

$ sha256sum ./Resonite_Data/Managed/TwitchLib.Communication.dll
4bf1ef23ccfcf0bcedac92e5c1abe0f82e74fb781e4f07847341a41ba15c6fd8  

$ sha256sum ./Headless/TwitchLib.Communication.dll
d7351489eafc6a26e8236ee0673861e26b78198c660831ec7d4c35f7f496d6a7

**Comment by zahndy** [comment]
Yeah this is still a problem
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/662702/e0d0579b-5081-4a97-979a-610c2bf44600)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/662702/e346b1f4-f006-4aa1-aebe-6027539aec57)

**Comment by Readun** [comment]
I also would ask for a revisit. It might be that we have multiple causes aswell.
I do have found out that my specific avatar is crashing Headlesses on equiping the Avatar. It loads fine when having it loaded via Favorites on joining said Linux headlesses!
 I sadly dont have the logs, but would be open to test it with someone else. (My own Windows Headless is still uneffected)

**Comment by Frooxius** [comment]
I just checked it. Our build script has not been copying some files, so some still got stuck with old version. I'll push a fix in the next update.

**Comment by bontebok** [comment]
> I just checked it. Our build script has not been copying some files, so some still got stuck with old version. I'll push a fix in the next update.

Thank you Froox. I will test it for this fix and any regression as soon as an update is available.

**Comment by liny-fox** [comment]
> I also would ask for a revisit. It might be that we have multiple causes aswell. I do have found out that my specific avatar is crashing Headlesses on equiping the Avatar. It loads fine when having it loaded via Favorites on joining said Linux headlesses! I sadly dont have the logs, but would be open to test it with someone else. (My own Windows Headless is still uneffected)
> 
> PS: Nevermind, Twitch. Twitch Chat Message Event Node to be exact.

To clarify, its the twitchinterface component, as soon as i add that my headless falls on its face and doesnt even restart the world.

**Comment by Frooxius** [comment]
The fix should now be in 2023.11.13.1343!

**Comment by liny-fox** [comment]
Can confirm, created an empty object, added the twitchinterface component and the world is still running.

**Comment by bontebok** [comment]
Tested on a docker w/ a steamcmd upgrade and a fresh install and can confirm this is now fixed.
