### ISSUE TITLE
Scroll wheel is backwards

### ISSUE THREAD

**Issue by iamgreaser** [Yellow-Dog-Man/Resonite-Issues#87]
### Describe the bug?

When you scroll up it scrolls down instead, and vice versa. This is a Unity bug.

### To Reproduce

Open the Linux client. Find something you can scroll through using the scroll wheel.

### Expected behavior

Scrolling down on the scroll wheel should scroll down.

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Linux

### Additional Context

NeosVR had a LinuxFixes mod which patched the Unity player to fix this: https://github.com/ljoonal/Neos-Mods#linux-fixes

The most legal workaround for this would be to detect if the scroll wheel needs reversing and do so. You could possibly have an "invert scroll wheel" setting for that, which may be something people might want anyway. I'd be tempted to make inversion applied based on the setting XOR the autodetection.

### Reporters

Too many to count.

**Comment by iamgreaser** [comment]
I highly doubt it would be different under different distros considering how X11 works.

And yes this is a Unity issue, it is fixed in later versions, and Tabletop Simulator has the same bug.

**Comment by yoshiyoshyosh** [comment]
> are you aware of which version the fix can first be found in?

after some googling, the only related thing I could find was [this bug in unity's tracker](https://issuetracker.unity3d.com/issues/linux-input-dot-mousescrolldelta-returns-reversed-values-in-linux-player). what's interesting is that they claim it was `Fixed in 2019.3.X`, but the version that Resonite reports in the unity `Player.log` is `2019.4.19f1`, yet it still exists as a bug.

**Comment by coolymike** [comment]
This is still an issue on the Linux native build. Without a Unity upgrade to a version that fixes it, this will need to be fixed by reversing the scroll direction on Linux in FrooxEngine.

**Comment by shiftyscales** [comment]
Is this issue still relevant even when running the Windows build through Proton, @iamgreaser? If not, this can probably be closed for now as the native Linux client has been deprecated indefinitely.

**Comment by yoshiyoshyosh** [comment]
> Is this issue still relevant even when running the Windows build through Proton, [@iamgreaser](https://github.com/iamgreaser)? If not, this can probably be closed for now as the native Linux client has been deprecated indefinitely.

no. it is also a unity issue, so it'll most likely go away once we're off unity

**Comment by shiftyscales** [comment]
I don't think there's anything further to be done here then thanks. Closing. :)
