### ISSUE TITLE
[Linux] Various Libraries Not Loaded Properly

### ISSUE THREAD

**Issue by yoshiyoshyosh** [Yellow-Dog-Man/Resonite-Issues#95]
### Describe the bug?

On Linux Native, various libraries do not get loaded by Resonite/Unity during launch, with varying degrees of severity associated. The following libraries have issues:

1. `libdl.so` - Resonite tries to load `libdl.so`, but some distributions do not provide this file/symlink. This can be worked around by symlinking this library yourself from `libdl.so.2`. [This might not be Resonite's problem](https://github.com/pauldotknopf/net-native-lib-loader/issues/3). Causes a crash on startup
2. `Assimp64.so` - Resonite tries to load `Assimp64.so`, but this is not provided with the build. Causes models to not be able to be imported. Trying my own `libassimp.so.5` causes a crash when trying to import models.
3. `libFreeimage.so` - The Unity runtime (at least that's my assumption given that it's only in `Player.log` tries to load `libFreeimage.so`, but since UNIX-likes are case-sensitive, it fails to load. Worked around by doing `ln -s libFreeImage.so libFreeimage.so` in the `Plugins` folder. Doesn't appear to affect anything
4. `brolib_x64.dll` - Resonite tries to load `brolib_x64.dll`, mistakenly thinking it's on Windows. A workaround is described by PLYSHKA below:
> it wants to load brolib from different directories
```
paths: /var/home/plyshka/Games/SteamLibrary/steamapps/common/Resonite/Resonite_Data/Managed|||
/var/home/plyshka/Games/SteamLibrary/steamapps/common/Resonite/Resonite_Data/Managed/runtimes/linux/native|||
runtimes/linux/native|||
/var/home/plyshka/Games/SteamLibrary/steamapps/common/Resonite/Resonite_Data/Managed/../../runtimes/linux/native|||
/var/home/plyshka/Games/SteamLibrary/steamapps/common/Resonitebin/runtimes/linux/native|||
file:/var/home/plyshka/Games/SteamLibrary/steamapps/common/Resonite/Resonite_Data/Managed/runtimes/linux/native
```
> i placed it to one of the paths path
Also need to recompile Brotli.Core.dll to remove regions of hardcoded windows = true in NativeLibraryLoader
As well as change target from 462 to 471
https://github.com/Yellow-Dog-Man/brotli.net
https://github.com/Yellow-Dog-Man/brotli.net/blob/master/Brotli.NET/Brotli.Core/Interop/NativeLibraryLoader.cs#L21-L28
it got loaded properly now

Doesn't have any visual side effects, but the logs do show `Brotli native encoding/decoding supported: False` when this happens, which might or might not affect anything.

### To Reproduce

1. Open Resonite on Linux native
2. Check logs

### Expected behavior

Libraries load properly.

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Linux

### Log Files

[Resonite Log](https://gist.github.com/yoshiyoshyosh/92ec126a7464a81c2faca24c6904efe2)

[Unity Player.log](https://gist.github.com/yoshiyoshyosh/61a3cb5cd6ab32e7e739d1b3dab65cba)

### Reporters

yosh, shocktail39 (`libdl.so` report), PLYSHKA (`brolib_x64` workaround)

**Comment by iamgreaser** [comment]
It seems that the non-native brotli implementation results in a failure to sync at least on my machine. But yeah, this'd be worth making a pull request for.

Of course, if the library were doing things the right way (as per the FreeImage bindings) as opposed to doing LoadLibrary/dlopen/whatever the hell macOS uses, we wouldn't have this problem.

**Comment by yoshiyoshyosh** [comment]
@Frooxius I'm @-ing you in this issue as a "tangential reply" to #1134. The Brotli issue and assimp issue still persist on the desktop Linux build. You can see my current log [here](https://gist.github.com/yoshiyoshyosh/a5b36176d36a3a8fd6e97c81281ef7a2). The only update seems to be that assimp no longer tries to look for the windows version of the library, rather the linux version (though the linux version of the library is not present). Brotli still thinks it's on windows.

**Comment by zahndy** [comment]
Since last update my headless instantly crashes because its missing multiple libraries.
[gameserv - 2024.2.2.906 - 2024-02-02 18_10_54.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14143235/gameserv.-.2024.2.2.906.-.2024-02-02.18_10_54.log)

**Comment by ProbablePrime** [comment]
Regardless of our decision on the Linux build, items like this one can still affect Headless Linux builds.

So I'm leaving this one open, but un-assigning Froox, the team are slowly making progress on this in other areas such as Cyro's build system updates but these specific issues I'll handle when I can.

**Comment by Frooxius** [comment]
Is this ok to close or are there more things? I've merged the Brotli fix in 2025.5.1.1282

**Comment by yoshiyoshyosh** [comment]
Last I remember from before the linux deprecation, the `libFreeimage.so` and `Assimp64.so` bugs still existed, but I don't think either of these are used by the headless client?

**Comment by Naia-love** [comment]
> so, it's september 2025 now, and I'm pretty sure that everything has somehow worked out here. it might've been related to cyro's linux works or jae's CI/CD stuff, but there's zero errors of library loading in the logs, nor have I seen any linux users get confused about this in the past half year or something. pretty sure it's fine to close now.

yeah at least for the library listed in the og issue

on my end there's still the discord error log (which whatever tbh)
also the viseme library too, but this dont spawn a few lines of errors at least (its silenced and just say "not found" or smght like that, compared to the discord one at least)
